spring:
  application:
    name: gitlab-kpa-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchClientAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/gitlab_analytics
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

elastic:
  host: localhost
  port: 9200
  scheme: http

gitlab:
  secret-token: ${{ GITLAB_SECRET-TOKEN }}
  base-url: ${{ GITLAB_BASE-URL }}
  username: ${{ GITLAB_USERNAME }}